### ISSUE TITLE
DHT Initial Configuration

### ISSUE THREAD

**Issue by RaulGracia** [jlouis/etorrent#105] opened 2011-04-08 09:29 UTC
Hi all,

I'm getting started with etorrent, but I'm experiencing problems with the initial configuration
of the application. Concretely, the problem is related with the DHT. I have built a release of the application and tested downloading a single torrent. Everything looks ok. 

However, when I enable the DHT option, the application crashes, dumping a crash.dump log file. The console and the crash.dump file show a non really helpful message:

{"Kernel pid Terminated", application_controller, "{application_start_failure,etorrent,{etorrent_app, start, [normal,[]]}}}"}

About libraries and software versions, I tried erlang versions RB13-04, RB14-02 and RB14-03.
I also tested versions 1.2.1 and 1.2.0 of etorrent as well as Ubuntu 10.10 and 10.04, without succeed. By doing this, I'm sure that is not a software incompatibility or a problem related with a specific software version.

Actually, I had a look to the sasl-error.log which gives a much more information that
the console or the crash.dump file. In my opinion, the error is related with the format
of the dht_state file or something related. That is, configuring and creating a file "etorrent_dht.persistent" the application crashes as aforementioned, and, if the file is just configured (without creating the file "etorrent_dht.persistent") the application shows, naturally, a "file does not exist error" (enoent) but the DHT related processes are at least initiated. I analyzed the process hierarchy by using appmon:start(). (Note that the same problem is retrieved using other file extensions as .txt for the dht persistence file) 

This is the crash trace in sasl-error.log:

CRASH REPORT==== 7-Apr-2011::19:06:46 ===
  crasher:
    initial call: etorrent_dht_state:init/1
    pid: <0.118.0>
    registered_name: []
    exception exit: {badarg,[{erlang,binary_to_term,[<<>>]},{etorrent_dht_state,load_state,1},{etorrent_dht_state,init,1},{gen_server,init_it,6},{proc_lib,init_p_do_apply,3}]}
      in function  gen_server:init_it/6
      in call from proc_lib:init_p_do_apply/3
    ancestors: [etorrent_dht_sup,etorrent_sup,<0.75.0>]
...

So, I'm wondering if I miss something in the DHT configuration. These are my configuration parameters:

[{etorrent,
  [ {port, 1729},
   {udp_port, 1730},
   {dht, true},
   {dht_port, 6882},
   {dht_state, "/home/lab144/Escritorio/etorrent/rel/etorrent/priv/etorrent_dht.persistent"},
   {dir, "/home/lab144/Escritorio/etorrent/rel/etorrent"},
   {logger_dir, "log"},
   {logger_fname, "etorrent.log"},
   {fast_resume_file, "/home/lab144/Escritorio/etorrent/rel/etorrent/priv/fast_resume.txt"},
   {max_peers, 200},
   {max_upload_rate, 175},
   {max_upload_slots, auto},
   {fs_watermark_high, 128},
   {fs_watermark_low, 100},
   {min_uploads, 2},
   {preallocation_strategy, sparse},
   {webui, true },
   {webui_logger_dir, "log/webui"},
   {webui_bind_address, {127,0,0,1}},
   {webui_port, 8080},
   {profiling, false},
   {use_upnp, true} ]},
 {mnesia, [{dir, "/home/lab144/Escritorio/etorrent/rel/etorrent"}]},
 {kernel, [{start_timer, true}]},
 {sasl, [{sasl_error_logger, {file, "log/sasl/sasl-error.log"}}, {errlog_type, error}]}
].

I will try to sort out what is happening in the dht initialization, but any kind of help will be really appreciated.
Thank you in advance,
Raúl.

**Comment by jlouis** [comment] 2011-04-08 09:36
Thank you for taking time to create a bug report. I'll investigate what is wrong and get back on what the problem happens to be. We better also get @klaar in on the run.

**Comment by ghost** [comment] 2011-04-08 09:55
I will have a look at it when i get home from work. The root of the cause is likely because of that missing file.

**Comment by jlouis** [comment] 2011-04-08 10:00
Also, to make it crystal clear.. is this the master branch? What does the output of `git describe` yield for the built code?

**Comment by RaulGracia** [comment] 2011-04-08 10:16
The command 'git describe' outputs "v1.2.1-450-gc4d0588". 
So, I it is the master branch, but I also tested releases from available packages v1.2.1 and v1.2.0, and the same error was retrieved when the DHT loaded the persistence file.

**Comment by RaulGracia** [comment] 2011-04-08 13:51
Good news, I found the problem :-)

Looking at the code, what happened was the following: when I created the release, I configured the client with both etorrent_dht.persistent and fast_resume.txt files, creating also both (empty) files.

The problem arises when the dht calls the function load_state(). That is, if the file configure exists (but it is empty), the function loads it attempting to fill up the routing table and so on. However, such function assumes that, if the file exists, it will contain information about the DHT state.  But, it is not always true, for instance, if the user creates an empty file to avoid "no such file" errors. 

So, that's it. As a suggestion to improve this point, a little bit more of information and instructions in the default configuration file or the project's "readme" would ease a lot getting started with etorrent. In addition, when the DHT is loading the state (load_state() function), it should handle the case of an incorrect/void persistent file either showing a message in this regard or ignoring such file replacing it by a correctly formed one.

Thanks a lot for your help :-),
Raúl.

**Comment by jlouis** [comment] 2011-04-08 14:12
Raul,

I agree fully with your analysis, excellent work. I will keep this issue open until we get a system that is a bit better at handling the error case and we have updated the configuration file with wording that explains the situation.

**Comment by ghost** [comment] 2011-04-08 16:42
I have pushed a fix and added tests to verify that it solved the case you're describing at:

https://github.com/klaar/etorrent/tree/dht-load-fix

**Comment by jlouis** [comment] 2011-04-08 20:36
Fix has been merged to master. CI-tool is happy :)

**Comment by RaulGracia** [comment] 2011-04-09 08:04
Nice to hear that :-)

**Comment by jlouis** [comment] 2011-08-23 14:16
This has been solved for some time now :)

**Closed as completed by jlouis** 2011-08-23 14:16 UTC
Labels: Bug, ULTRA-solved
